_wandb:
    value:
        cli_version: 0.21.0
        e:
            100o7whhgy752l1ymnak4tehaohh6tnw:
                args:
                    - --help
                codePath: src/OUP.py
                codePathLocal: OUP.py
                cpu_count: 56
                cpu_count_logical: 112
                cudaVersion: "12.3"
                disk:
                    /:
                        total: "32186826752"
                        used: "24549445632"
                email: jiaweixing99@gmail.com
                executable: /grid/siepel/home/xing/.conda/envs/OUP/bin/python
                git:
                    commit: e0da42529074a537200aa0219d37c0a9866042ab
                    remote: https://github.com/Jiawei-Xing/SingleCellStochastics
                gpu: NVIDIA H100 NVL
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "100485038080"
                      name: NVIDIA H100 NVL
                      uuid: GPU-ff3a6be6-3814-590e-f04c-0bca8b867b4d
                host: bamgpu26
                memory:
                    total: "1081663565824"
                os: Linux-4.18.0-513.18.1.el8_9.x86_64-x86_64-with-glibc2.28
                program: /grid/siepel/home/xing/gene_expression_evolution/SingleCellStochastics/src/OUP.py
                python: CPython 3.12.9
                root: /grid/siepel/home/xing/gene_expression_evolution/SingleCellStochastics/src
                slurm:
                    cluster_name: slurm
                    conf: /cm/shared/apps/slurm/var/etc/slurm/slurm.conf
                    cpus_on_node: "2"
                    distribution: cyclic
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: siepellab
                    job_cpus_per_node: "2"
                    job_end_time: "1756166671"
                    job_gid: "11037"
                    job_group: siepel lab staff
                    job_id: "111021"
                    job_name: bash
                    job_nodelist: bamgpu26
                    job_num_nodes: "1"
                    job_partition: gpuq
                    job_qos: default
                    job_start_time: "1756159470"
                    job_uid: "11387"
                    job_user: xing
                    jobid: "111021"
                    launch_node_ipaddr: 172.20.0.71
                    localid: "0"
                    mem_per_node: "40960"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: bamgpu26
                    nprocs: "1"
                    ntasks: "1"
                    prio_process: "0"
                    procid: "0"
                    pty_port: "38665"
                    pty_win_col: "219"
                    pty_win_row: "9"
                    srun_comm_host: 172.20.0.71
                    srun_comm_port: "33779"
                    step_gpus: "2"
                    step_id: "0"
                    step_launcher_port: "33779"
                    step_nodelist: bamgpu26
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /grid/siepel/home/xing
                    submit_host: bamdev3
                    task_pid: "1885367"
                    tasks_per_node: "1"
                    tmpdir: /tmp/slurm_tmp/111021
                    topology_addr: bamgpu26
                    topology_addr_pattern: node
                    umask: "0022"
                startedAt: "2025-08-25T22:17:00.527329Z"
                writerId: 100o7whhgy752l1ymnak4tehaohh6tnw
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 53
            "2":
                - 1
                - 53
            "3":
                - 13
            "4": 3.12.9
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
